apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-python-app-service
spec:
  selector:
    app: {{ .Release.Name }}-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
